import { createHash } from "node:crypto";
import type {
  Artifact,
  ProviderProfile,
  StudioSnapshot,
  WorkflowNode,
} from "./model.js";
import { StudioSnapshotSchema } from "./model.js";

const VERIFIED_AT = "2026-08-28";

function version(id: string, data: unknown, now: string): Artifact["versions"][number] {
  return {
    id: `${id}-v1`,
    createdAt: now,
    sha256: createHash("sha256").update(JSON.stringify(data) ?? "null").digest("hex"),
    source: "seed",
    data,
  };
}

function artifact(id: string, kind: string, data: unknown, now: string): Artifact {
  const initial = version(id, data, now);
  return { id, kind, activeVersionId: initial.id, versions: [initial] };
}

function node(
  id: string,
  label: string,
  phase: WorkflowNode["phase"],
  role: string,
  capability: string,
  inputArtifactIds: string[],
  outputArtifactIds: string[],
  options: Partial<WorkflowNode> = {},
): WorkflowNode {
  return {
    id,
    label,
    phase,
    role,
    capability,
    status: "succeeded",
    inputArtifactIds,
    inputVersionIds: [],
    outputArtifactIds,
    prerequisiteNodeIds: [],
    estimatedCostCny: 0,
    ...options,
  };
}

function providers(): ProviderProfile[] {
  return [
    {
      id: "local-ollama-production",
      capability: "script.segment",
      label: "Ollama 本地制作模型",
      description: "按已核验 claim、动态角色和节目蓝图生成结构化长脚本与音乐 Cue。",
      deployment: "local",
      billing: { type: "local_compute", unit: "run", rate: 0, unitSize: 1, currency: "CNY" },
      rights: { commercialUse: "allowed", attributionRequired: false, voiceConsentRequired: false },
      languages: ["zh-CN"],
      modes: ["动态角色", "长脚本", "结构化 Cue", "claim 引用约束"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要本机 Ollama，并设置 TOKEN_TALK_PRODUCTION_MODEL" },
    },
    {
      id: "local-macos-say",
      capability: "voice.synthesize",
      label: "macOS 系统配音",
      description: "用于零调用成本的工作流验证，不作为正式节目默认声音。",
      deployment: "local",
      billing: { type: "local_compute", unit: "compute_second", rate: 0, unitSize: 1, currency: "CNY" },
      rights: { commercialUse: "allowed", attributionRequired: false, voiceConsentRequired: false },
      languages: ["zh-CN", "en-US"],
      modes: ["链路验证"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "ready" },
    },
    {
      id: "alibaba-qwen-tts",
      capability: "voice.synthesize",
      label: "Qwen / CosyVoice",
      description: "中文声音设计、复刻与长文本候选，具体价格按模型和区域配置。",
      deployment: "external",
      billing: { type: "metered", unit: "character", rate: 0.8, unitSize: 10_000, currency: "CNY" },
      quota: { amount: 110_000, unit: "character", renewal: "introductory", eligibility: "开通后 90 天；地域与具体模型需在控制台确认" },
      rights: {
        commercialUse: "unknown",
        attributionRequired: false,
        licenseUrl: "https://help.aliyun.com/en/model-studio/model-pricing",
        voiceConsentRequired: true,
      },
      languages: ["zh-CN", "en-US"],
      modes: ["声音设计", "声音复刻", "长文本"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 DASHSCOPE_API_KEY 并确认具体模型条款" },
    },
    {
      id: "volcengine-doubao-tts",
      capability: "voice.synthesize",
      label: "豆包语音合成",
      description: "面向中文情绪表达与声音复刻的按量候选。",
      deployment: "external",
      billing: { type: "metered", unit: "character", rate: 4.5, unitSize: 10_000, currency: "CNY" },
      rights: {
        commercialUse: "unknown",
        attributionRequired: false,
        licenseUrl: "https://www.volcengine.com/product/ark",
        voiceConsentRequired: true,
      },
      languages: ["zh-CN"],
      modes: ["情绪控制", "声音复刻"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 ARK_API_KEY 并确认节目发行条款" },
    },
    {
      id: "elevenlabs-v3",
      capability: "voice.synthesize",
      label: "ElevenLabs v3",
      description: "高表现力多语种声音候选，免费额度不能用于商业节目。",
      deployment: "external",
      billing: { type: "metered", unit: "character", rate: 0.1, unitSize: 1_000, currency: "USD" },
      quota: { amount: 10_000, unit: "character", renewal: "monthly" },
      rights: {
        commercialUse: "restricted",
        attributionRequired: true,
        licenseUrl: "https://elevenlabs.io/docs/overview/capabilities/text-to-speech",
        voiceConsentRequired: true,
      },
      languages: ["zh-CN", "en-US"],
      modes: ["情绪标签", "多角色", "声音设计"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 ELEVENLABS_API_KEY 和付费商用方案" },
    },
    {
      id: "internal-music-library",
      capability: "music.retrieve",
      label: "内部审核音乐库",
      description: "保存已核验来源、授权范围和系列声音资产。",
      deployment: "local",
      billing: { type: "local_compute", unit: "run", rate: 0, unitSize: 1, currency: "CNY" },
      rights: { commercialUse: "allowed", attributionRequired: false, voiceConsentRequired: false },
      languages: [],
      modes: ["片头", "转场", "铺底"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "ready" },
    },
    {
      id: "stable-audio-3",
      capability: "music.generate",
      label: "Stable Audio 3.0",
      description: "按次生成音乐候选，商用范围受 Community License 收入门槛约束。",
      deployment: "external",
      billing: { type: "metered", unit: "run", rate: 0.26, unitSize: 1, currency: "USD" },
      quota: { amount: 25, unit: "run", renewal: "introductory" },
      rights: {
        commercialUse: "restricted",
        attributionRequired: false,
        licenseUrl: "https://stability.ai/license",
        voiceConsentRequired: false,
      },
      languages: [],
      modes: ["音乐生成", "音频参考"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 STABILITY_API_KEY 和收入条件核验" },
    },
    {
      id: "research-agent-orchestrator",
      capability: "research.search",
      label: "免费研究 Agent",
      description: "并发调度免费知识源，保存逐源尝试与待核验来源账本。",
      deployment: "local",
      billing: { type: "free", unit: "run", rate: 0, unitSize: 1, currency: "CNY" },
      rights: { commercialUse: "allowed", attributionRequired: false, voiceConsentRequired: false },
      languages: ["zh-CN", "en-US"],
      modes: ["多源检索", "失败隔离", "来源账本"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "ready" },
    },
    {
      id: "human-research",
      capability: "research.search",
      label: "人工来源核验",
      description: "由主编逐条确认来源归属、链接与独立性后通过资料门禁。",
      deployment: "local",
      billing: { type: "free", unit: "run", rate: 0, unitSize: 1, currency: "CNY" },
      rights: { commercialUse: "allowed", attributionRequired: false, voiceConsentRequired: false },
      languages: ["zh-CN", "en-US"],
      modes: ["来源核验", "独立性归组"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "ready" },
    },
    {
      id: "wikipedia-zh",
      capability: "research.search",
      label: "中文维基百科",
      description: "免费发现背景资料与概念线索；结果必须回到原始引用继续核验。",
      deployment: "external",
      billing: { type: "free", unit: "request", rate: 0, unitSize: 1, currency: "CNY" },
      rights: {
        commercialUse: "allowed",
        attributionRequired: true,
        licenseUrl: "https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use",
        voiceConsentRequired: false,
      },
      languages: ["zh-CN"],
      modes: ["百科检索", "背景线索"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 TOKEN_TALK_RESEARCH_USER_AGENT（含联系 URL 或邮箱）" },
    },
    {
      id: "crossref-public",
      capability: "research.search",
      label: "Crossref 公共元数据",
      description: "免费检索论文与图书 DOI 元数据，用于发现可追溯的学术来源。",
      deployment: "external",
      billing: { type: "free", unit: "request", rate: 0, unitSize: 1, currency: "CNY" },
      rights: {
        commercialUse: "allowed",
        attributionRequired: false,
        licenseUrl: "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
        voiceConsentRequired: false,
      },
      languages: [],
      modes: ["论文检索", "DOI 元数据", "出版信息"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "ready" },
    },
    {
      id: "brave-search",
      capability: "research.search",
      label: "Brave Search API",
      description: "为选题和资料包提供带来源的搜索结果。",
      deployment: "external",
      billing: { type: "metered", unit: "request", rate: 5, unitSize: 1_000, currency: "USD" },
      quota: { amount: 1_000, unit: "request", renewal: "monthly", eligibility: "按 $5/1000 次与每月 $5 credit 换算；需遵守 attribution 要求" },
      rights: {
        commercialUse: "allowed",
        attributionRequired: true,
        licenseUrl: "https://brave.com/search/api/",
        voiceConsentRequired: false,
      },
      languages: [],
      modes: ["网页", "新闻", "图片"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 BRAVE_SEARCH_API_KEY" },
    },
    {
      id: "gpt-image",
      capability: "image.generate",
      label: "GPT Image",
      description: "节目与单集封面候选生成。",
      deployment: "external",
      billing: { type: "metered", unit: "image", rate: 0.034, unitSize: 1, currency: "USD" },
      rights: {
        commercialUse: "allowed",
        attributionRequired: false,
        licenseUrl: "https://developers.openai.com/api/docs/models/gpt-image-1.5",
        voiceConsentRequired: false,
      },
      languages: [],
      modes: ["1024x1024", "封面候选"],
      verifiedAt: VERIFIED_AT,
      availability: { status: "needs_config", reason: "需要 OPENAI_API_KEY" },
    },
  ];
}

export function createSeedSnapshot(now = new Date().toISOString()): StudioSnapshot {
  const artifacts = [
    artifact("artifact-brief", "episode-brief", { title: "为什么我们还需要认真读《思考，快与慢》" }, now),
    artifact("artifact-sources", "source-packet", { sources: 6, verified: 5 }, now),
    artifact("artifact-claims", "claim-ledger", { claims: 12, needsReview: 2 }, now),
    artifact("artifact-research-audit", "research-audit", { verdict: "pass", findings: [] }, now),
    artifact("artifact-cast", "cast-plan", {
      status: "draft",
      policy: "dynamic",
      roles: [
        { id: "guide", name: "引导者", responsibility: "维持主问题与节目节奏" },
        { id: "challenger", name: "质疑者", responsibility: "寻找反例并追问证据边界" },
      ],
    }, now),
    artifact("artifact-blueprint", "episode-blueprint", { chapters: 5, targetMinutes: 38 }, now),
    artifact("artifact-emotion", "emotional-arc", { beats: ["好奇", "冲突", "释然"] }, now),
    artifact("artifact-segment-1", "segment", { title: "直觉究竟帮了我们什么" }, now),
    artifact("artifact-script", "episode-script", { status: "assembled" }, now),
    artifact("artifact-script-audit", "script-audit", { verdict: "pass", findings: [] }, now),
    artifact("artifact-release-copy", "release.copy", {
      status: "ready",
      episodeTitle: "《思考，快与慢》：直觉可靠吗？",
      summary: "从证据边界重新讨论直觉、偏差与判断。",
      showNotes: ["直觉真正擅长什么", "证据能回答到哪里"],
      keywords: ["认知科学", "判断", "读书"],
    }, now),
    artifact("artifact-voices", "voice-plan", {
      status: "confirmed",
      confirmed: true,
      selections: [
        { role: "引导者", providerId: "local-macos-say", voiceId: "Tingting", use: "preview_only" },
        { role: "质疑者", providerId: "local-macos-say", voiceId: "Eddy (中文（中国大陆）)", use: "preview_only" },
      ],
    }, now),
    artifact("artifact-cues", "music-cue-sheet", { cues: 4, silenceOptions: 2 }, now),
    artifact("artifact-audio", "audio-master", { durationSeconds: 2_280 }, now),
    artifact("artifact-audio-audit", "audio-audit", { verdict: "pass", findings: [] }, now),
    artifact("artifact-visuals", "visual-pack", { covers: 3, chapterCards: 5 }, now),
    artifact("artifact-publish", "publish-package", { status: "draft" }, now),
  ];

  const nodes = [
    node("episode-brief", "单集 Brief", "planning", "主编", "editorial.brief", [], ["artifact-brief"]),
    node("source-packet", "资料包", "planning", "研究员", "research.search", ["artifact-brief"], ["artifact-sources"], {
      providerId: "brave-search",
      modelId: "web-search",
      estimatedCostCny: 0.18,
      authorizedCostCny: 0.5,
      actualCostCny: 0.16,
    }),
    node("claim-ledger", "论点账本", "planning", "事实编辑", "research.claims", ["artifact-sources"], ["artifact-claims"]),
    node("evidence-audit", "证据审计", "planning", "独立审计 Agent", "research.audit", ["artifact-sources", "artifact-claims"], ["artifact-research-audit"]),
    node("cast-plan", "角色编排", "planning", "Casting Director", "cast.plan", ["artifact-brief", "artifact-claims"], ["artifact-cast"]),
    node("episode-blueprint", "节目蓝图", "planning", "节目架构师", "episode.blueprint", ["artifact-claims", "artifact-cast"], ["artifact-blueprint"]),
    node("emotional-arc", "情绪曲线", "planning", "声音导演", "audio.emotional-arc", ["artifact-blueprint"], ["artifact-emotion"]),
    node("segment-room-1", "章节 1", "production", "分段编剧", "script.segment", ["artifact-blueprint", "artifact-sources"], ["artifact-segment-1"]),
    node("showrunner-assembly", "整集统筹", "production", "Showrunner", "script.assemble", ["artifact-segment-1"], ["artifact-script"]),
    node("script-audit", "脚本红队审计", "production", "独立审计 Agent", "script.audit", ["artifact-script"], ["artifact-script-audit"]),
    node("script-repair", "脚本定向返修", "production", "返修编辑", "script.repair", ["artifact-script", "artifact-script-audit"], ["artifact-script"]),
    node("release-editorial", "标题、简介与 Show Notes", "production", "发行编辑", "release.copy", ["artifact-script", "artifact-blueprint", "artifact-sources"], ["artifact-release-copy"], { prerequisiteNodeIds: ["script-repair"] }),
    node("voice-casting", "声音试演", "production", "声音导演", "voice.synthesize", ["artifact-script", "artifact-cast"], ["artifact-voices"], { prerequisiteNodeIds: ["script-repair"] }),
    node("music-cue-sheet", "音乐 Cue", "production", "音乐导演", "music.plan", ["artifact-script", "artifact-emotion"], ["artifact-cues"], { prerequisiteNodeIds: ["script-repair"] }),
    node("audio-mix", "声音混合", "production", "声音导演", "audio.render", ["artifact-script", "artifact-voices", "artifact-cues"], ["artifact-audio"]),
    node("visual-pack", "视觉资产", "production", "视觉编辑", "image.generate", ["artifact-brief"], ["artifact-visuals"], {
      providerId: "gpt-image",
      modelId: "gpt-image-1.5",
      estimatedCostCny: 0.72,
      authorizedCostCny: 1.5,
      actualCostCny: 0.68,
    }),
    node("audio-audit", "成片质量审计", "production", "独立审计 Agent", "audio.audit", ["artifact-audio"], ["artifact-audio-audit"]),
    node("publish-package", "发布包", "production", "发行制作人", "publish.package", ["artifact-audio", "artifact-visuals", "artifact-audio-audit", "artifact-release-copy"], ["artifact-publish"], { prerequisiteNodeIds: ["audio-audit", "release-editorial"] }),
  ];

  for (const workflowNode of nodes) {
    workflowNode.inputVersionIds = workflowNode.inputArtifactIds.flatMap((artifactId) => {
      const input = artifacts.find((candidate) => candidate.id === artifactId);
      return input ? [input.activeVersionId] : [];
    });
  }

  return StudioSnapshotSchema.parse({
    schemaVersion: 1,
    updatedAt: now,
    series: [{
      id: "series-deep-reading",
      title: "Token Talk 读书会",
      promise: "不复述一本书，而是把它谈成值得继续追问的问题",
      audience: "希望深入理解一本书，也愿意听见分歧的中文听众",
      castPolicy: { mode: "dynamic", recurringRoleIds: [], minSpeakers: 1, maxSpeakers: 4 },
      sonicBible: {
        musicPolicy: "narrative",
        palette: ["prepared-piano", "soft-percussion", "warm-synth"],
        exclusions: ["煽情弦乐", "持续高密度铺底"],
      },
      memory: ["优先讨论书中仍有争议的结论"],
    }],
    recipes: [
      {
        id: "rapid-topic-v1",
        label: "热点深谈",
        description: "快速响应正在发生的话题，但仍完成证据核验、章节推演与完整论证。",
        contentProduct: "rapid",
        targetMinutes: { min: 15, max: 25 },
        musicPolicy: "minimal",
        budgetPolicy: "economy",
        capabilityIds: ["research.search", "cast.plan", "episode.blueprint", "script.segment", "release.copy", "music.plan", "voice.synthesize", "audio.render", "image.generate", "publish.package"],
        estimatedCostCny: { min: 0, max: 3 },
      },
      {
        id: "deep-reading-v1",
        label: "深度专题",
        description: "建立资料与事实账本、动态角色及多章节讨论，适合长期留存的深度节目。",
        contentProduct: "durable",
        targetMinutes: { min: 30, max: 60 },
        musicPolicy: "narrative",
        budgetPolicy: "balanced",
        capabilityIds: ["research.search", "research.claims", "cast.plan", "episode.blueprint", "script.segment", "script.assemble", "release.copy", "music.plan", "voice.synthesize", "audio.render", "image.generate", "publish.package"],
        estimatedCostCny: { min: 2, max: 18 },
      },
    ],
    providers: providers(),
    runs: [{
      id: "run-deep-reading",
      title: "《思考，快与慢》：直觉可靠吗？",
      seriesId: "series-deep-reading",
      recipeId: "deep-reading-v1",
      status: "needs_human",
      createdAt: now,
      updatedAt: now,
      nodes,
      artifacts,
      spendAuthorizations: [],
      executionReceipts: [],
    }],
    opportunities: [],
  });
}
